version: "3.3"
    
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-datenbank
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    
  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysqluser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mysql-datenbank
volumes:
  db_data: {}